configured_endpoints: 34
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/opencode%2Fopencode-7d370d30ae7aba41bef18ec75399d84abbeea6ed1adb6ceff7221dfd27fe06dc.yml
openapi_spec_hash: bb266bf0d43d6ac11b14838977c8c7a5
config_hash: 92d12e018bb9e4f5a6f9ea9e277d403e
